const crimes = [
  "All",
  "Theft",
  "Burglary",
  "Robbery",
  "Assault",
  "Murder",
  "Arson",
  "Fraud",
  "Vandalism",
  "Drug Possession",
  "Drug Trafficking",
  "Kidnapping",
  "Domestic Violence",
  "Cybercrime",
  "Forgery",
  "Embezzlement",
  "Money Laundering",
  "Terrorism",
  "Human Trafficking",
  "Sexual Assault",
  "Hate Crime",
  "Driving Under Influence",
  "Bribery",
  "Stalking",
  "Weapons Possession",
  "Public Intoxication",
  "Tax Evasion",
  "Identity Theft",
  "Extortion",
  "Counterfeiting",
  "Animal Cruelty",
  "Child Abuse",
  "Insider Trading",
  "Obstruction of Justice",
  "Perjury",
  "Prostitution",
  "Smuggling",
  "Loitering",
  "Trespassing",
  "Disorderly Conduct",
  "Public Nuisance",
  "Contempt of Court",
  "Illegal Gambling",
  "Environmental Crime",
  "Forgery of Documents",
  "Hacking",
  "Kidnapping for Ransom",
  "Sedition",
  "Treason",
  "Bribery of Public Officials",
  "Piracy",
  "Cyberbullying",
  "Money Counterfeiting",
  "Illegal Possession of Firearms",
  "Tax Fraud",
  "Pollution Violations",
  "Hit and Run",
  "Smuggling of Contraband",
  "Forgery of Currency",
  "Illegal Logging",
  "Illegal Mining",
  "Organized Crime",
  "Gang-related Crime",
  "Public Corruption",
  "Intellectual Property Theft",
  "Child Pornography",
  "Sex Trafficking",
  "Illegal Wildlife Trade",
  "Drug Manufacturing",
  "Unauthorized Use of Property",
  "Bank Fraud",
  "Credit Card Fraud",
  "Insurance Fraud",
  "Election Fraud",
  "Harassment",
  "Cyber Espionage",
  "Breaking and Entering",
  "Resisting Arrest",
  "DUI Manslaughter",
  "Illegal Detention",
  "False Imprisonment",
  "Money Laundering",
  "Violating Probation",
  "Weapon Smuggling",
  "Cyber Terrorism",
  "Illegal Wiretapping",
  "Cyber Stalking",
  "Larceny",
  "Illegal Dumping",
  "Financial Exploitation",
  "Ponzi Scheme",
  "Blackmail",
  "Armed Robbery",
];

export default crimes;
